#!/usr/bin/env python
#-*- coding: utf-8 -*-

### Many thanks to http://www.travisglines.com/web-coding/python-xml-parser-tutorial
# Common use:
import sys
import re

#import easy to use xml parser called minidom:
from xml.dom.minidom import parseString


#open the xml file for reading:
file = open(sys.argv[1],'r')

#convert to string:
data = file.readlines()

#close file:
file.close()

#parse the xml you got from the file
dom = parseString(data)

# List containg all desired values
chosenStructure = []

# Find the structure that has the 'Ground Speeds' as the first element, this
# one will be the one we need.
for i in range(len(dom.getElementsByTagName('Folder'))):

    # Trying to match 'Ground Speeds'
    mystr = dom.getElementsByTagName('Folder')[i].getElementsByTagName('name')[0].toxml('utf-8')

    if re.sub("</?name>",'',mystr) == 'Ground Speeds':
        global chosenStructure = dom.getElementsByTagName('Folder')[i].getElementsByTagName('name')
        break

# Ok, now we have the structure that has all speeds we need. Its necessary to
# change value colors according to .colorCode files generated by Ranger
# classes.

# Must take chosenStructure[i].getElementsByTagName('color') or something
# Suggestions are:
# l=[i.getElementsByTagName('color') for i in dom.getElementsByTagName('Folder')[1].getElementsByTagName('Style')]


